language: node_js
node_js: node
cache: npm

branches:
  only:
  - development

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      script: npm run deploy
