language: node_js
node_js: node
cache: npm

branches:
  only:
  - development

script:
  - npm run lint

after_success:
  - npm run build
  - .travis/fetch-github-chart.sh
  - .travis/commit-and-push.sh
